---
title: "Etude des poches de PR2"
author: "Leslie REGAD et Akram HECINI"
date: '`r Sys.Date()`'
output:
  html_document:
    code_folding: show #hide
    self_contained: yes
    fig_caption: yes
    highlight: pygments #pour les sorties R
    theme: spacelab
    toc: yes  #for add table of contents
    toc_depth: 3
    toc_float: yes
    df_print: paged
    keep_md: yes  #pour garder le .md after run
  slidy_presentation:
    smart: no
    slide_level: 2
    self_contained: yes
    fig_caption: yes
    fig_height: 6
    fig_width: 7
    highlight: tango
    incremental: no
    keep_md: yes
    smaller: yes
    theme: cerulean
    toc: yes
    widescreen: yes
  ioslides_presentation:
    slide_level: 2
    self_contained: no
    colortheme: dolphin
    fig_caption: yes
    fig_height: 6
    fig_width: 7
    fonttheme: structurebold
    highlight: tango
    smaller: yes
    toc: yes
    widescreen: yes
  pdf_document:
    fig_caption: yes
    highlight: zenburn
    toc: yes
    toc_depth: 3
  beamer_presentation:
    colortheme: dolphin
    fig_caption: yes
    fig_height: 6
    fig_width: 7
    fonttheme: structurebold
    highlight: tango
    incremental: no
    keep_tex: no
    slide_level: 2
    theme: Montpellier
    toc: yes
font-import: http://fonts.googleapis.com/css?family=Risque
font-family: Garamond
transition: linear
---

```{r include=FALSE, echo=FALSE, eval=TRUE}
library(knitr)
library(pheatmap)
#library(kableExtra)
# library(formattable)
options(width = 300)
# options(encoding = 'UTF-8')
knitr::opts_chunk$set(
  fig.width = 7, fig.height = 5, 
  fig.path = 'figures/suivi_',
  fig.align = "center", 
  size = "tiny", 
  echo = TRUE, eval = TRUE, 
  warning = FALSE, message = FALSE, 
  results = TRUE, comment = "")
options(scipen = 12) ## Max number of digits for non-scientific notation
# knitr::asis_output("\\footnotesize")
```


# Objectif du projet

Le but du projet est d'étudier les différents sites de liaison de la protéase du VIH-2 (PR2) dans le but d'identifier de nouveau site de liaison



# Data disponibles 

* le répertoire `data/PR2_19` contient les fichiers PDB des 19 structures de PR2 disponibles dans la PDB.


# Protocole

* Estimation des poches des 19 PR2 à l'aide de Fpocket  
    + étape 1 : A l'aide du programme Fpocket, identifier toutes les poches des 19 PR2. 
    + étape 2 : calcul du score de druggabilité de chaque poche à l'aide du logiciel PockDrug.  
    + étape 3 : calcul du chevauchement entre toutes les poches, pour identifier les poches similaires des différentes protéines.  

* Estimation des poches des 19 PR2 à l'aide de FTMap  
    + étape 1 : A l'aide du programme FTMap, identifier toutes les poches des 19 PR2. 
    + étape 2 : comparer les résultats avec les poches obtenues avec Fpocket
    
* Classification des poches basées sur leur description  
    + étape 1 : calculer les descripteurs de différentes poches estimées
    + étape 2 : classification des poches

* Selection des poches d'intérêt

* Etude des interactions entre les résidus de ces poches et les autres résidus des PR2.