---
title: "meeting 15/03/2019"
author: "Leslie REGAD et Akram HECINI"
date: '`r Sys.Date()`'
output:
  html_document:
    code_folding: show #hide
    self_contained: yes
    fig_caption: yes
    highlight: pygments #pour les sorties R
    theme: spacelab
    toc: yes  #for add table of contents
    toc_depth: 3
    toc_float: yes
    df_print: paged
    keep_md: no  #pour garder le .md after run
  slidy_presentation:
    smart: no
    slide_level: 2
    self_contained: yes
    fig_caption: yes
    fig_height: 6
    fig_width: 7
    highlight: tango
    incremental: no
    keep_md: yes
    smaller: yes
    theme: cerulean
    toc: yes
    widescreen: yes
  ioslides_presentation:
    slide_level: 2
    self_contained: no
    colortheme: dolphin
    fig_caption: yes
    fig_height: 6
    fig_width: 7
    fonttheme: structurebold
    highlight: tango
    smaller: yes
    toc: yes
    widescreen: yes
  pdf_document:
    fig_caption: yes
    highlight: zenburn
    toc: yes
    toc_depth: 3
  beamer_presentation:
    colortheme: dolphin
    fig_caption: yes
    fig_height: 6
    fig_width: 7
    fonttheme: structurebold
    highlight: tango
    incremental: no
    keep_tex: no
    slide_level: 2
    theme: Montpellier
    toc: yes
font-import: http://fonts.googleapis.com/css?family=Risque
font-family: Garamond
transition: linear
---

```{r include=FALSE, echo=FALSE, eval=TRUE}
library(knitr)
library(pheatmap)
#library(kableExtra)
# library(formattable)
options(width = 300)
# options(encoding = 'UTF-8')
knitr::opts_chunk$set(
  fig.width = 7, fig.height = 5, 
  fig.path = 'figures/suivi_',
  fig.align = "center", 
  size = "tiny", 
  echo = TRUE, eval = TRUE, 
  warning = FALSE, message = FALSE, 
  results = TRUE, comment = "")
options(scipen = 12) ## Max number of digits for non-scientific notation
# knitr::asis_output("\\footnotesize")
```

**Participants** : Leslie Regad (LR) et Akram Hecini (AH)

[Résultats obtenus par Akram] (../pocket_PR2.html)
# Estimation des poches

Akram a travaillé sur l'estimation des poches des 19 PR2  

* problèmes rencontrés   
    + PockDrug ne calcule pas la druggabilité pour des poches trop petites   
    $\rightarrow$ LR essaie de trouver le programme pour voir si on peut supprimer cette condition  
    + PockDrug et fpocket ne donne pas les mêmes poches (en termes de résidus)  
    Exemple sur 1HSH :   
    Regarder si dans pockDrug le paramètre du diamètre a changé.


# Caractérisation des poches

* pour chaque protéine, AH a regardé combien de poches sont extraites  
* AK doit aussi regarder la taille de l'ensemble des poches : 
    + en définissant taille des poches comme le nombre de résidus  
    + en définissant taille des poches comme le nombre d'atomes  
    Regarder cela pour l'ensemble des protéines et pour chaque protéine
    
* Il faut maintenant calculé le chevauchement entre toutes les poches pour identifier les poches communes.  
  LR a fourni le programme `script/scrOverlapScore/main_Overlap_arg.py`   
  Pour utiliser ce programme AK doit : 
      + créez un répertoire qui contient les fichiers pdb des poches extraites des 19 PR2 en les renommants  
      + créez un répertoire qui contient les fichiers pdb des 19 PR2.  
      + lancer le programme sur ces données  
      + analyser les résultats pour déterminer quelles sont les poches similaires.
    



